name: SoupFFA
main: SoupFFA\SoupFFA
version: 1.5.0
api: [3.0.0-ALPHA5, 2.0.0, 1.12.0]
author: McpeBooster
website: Twitter.com/McpeBooster

commands:
  soupffa:
    description: Join SoupFFA directly per Command
